### ISSUE TITLE
Django admin user restrictions

### ISSUE THREAD

**Issue by jeroenpeters1986** [jeroenpeters1986/pyBudgie#6]
Restrict users to their own objects in the Django admin, if user is not a super user

**Comment by Adeboye-daniel** [comment]
You mean you want user to access your admin panel but they would be restricted to some things right

**Comment by jeroenpeters1986** [comment]
> You mean you want user to access your admin panel but they would be restricted to some things right

Yes, to their own instances

**Comment by Adeboye-daniel** [comment]
Well I would rather advice you to create a separate page apart from the admin panel and you set permissions for your users

**Comment by Adeboye-daniel** [comment]
> Well I would rather advice you to create a separate page apart from the admin panel and you set permissions for your users 

I think it won't be ok giving users access to the admin panel

**Comment by jeroenpeters1986** [comment]
Hi again. Thanks for your advice. I know what you mean, but this private project (not on Github I see now, but what it will be used for) is for me a way to do more with tests, black, linters etc and on the other hand a way to see how I can leverage the admin without having to build something myself. In my work-projects I do not conduct this kind of codestyle

**Comment by Adeboye-daniel** [comment]
> Hi again. Thanks for your advice. I know what you mean, but this private project (not on Github I see now, but what it will be used for) is for me a way to do more with tests, black, linters etc and on the other hand a way to see how I can leverage the admin without having to build something myself. In my work-projects I do not conduct this kind of codestyle

Ok now I understand
